### ISSUE TITLE
Given a list of numbers representing points in an infinite plane, find k closest points to (0,0).

### ISSUE THREAD

**Issue by Noitidart** [wonjoolee95/adapt-or-die#1]
https://programmingpraxis.com/2012/11/27/amazon-interview-question/

Please close whenever, just sharing I had fun reading that one today.

**Comment by wonjoolee95** [comment]
I like it! I'll put up a solution for this by tomorrow.

**Comment by wonjoolee95** [comment]
Please open as many as issues you want! I'll try my best to solve all of the open issues :)

**Comment by Noitidart** [comment]
<3 <3 <3 Sorry I didnt' mean to throw work at you and be like hey do this haha. Sorry man just had a fun

**Comment by Noitidart** [comment]
> 
> 
> Please open as many as issues you want! I'll try my best to solve all of the open issues :)

Please definitely close some issues saying "i think this is stupid and shouldn't be in here". haha

I'll create issue of questions I think miiight be nice. I'm not sure if it's nice or not. Need your thoughts on it. If you think its got nice learnings then yes please but if not totally lets close it! :D

**Comment by wonjoolee95** [comment]
For sure, sounds good :))))

**Comment by wonjoolee95** [comment]
Update title to remove "heap", just to remove the hint that this is supposed to use a heap.

**Comment by Noitidart** [comment]
Thanks man! That would be just like our weekend sessions! But remotish! Like we both bring material then we decide, nah this isn't broad or good enough learning.

I can even post my solutions too in the issue to discuss! :D

**Comment by wonjoolee95** [comment]
Yeah! And we can have mock phone interviews as well haha.

**Comment by Noitidart** [comment]
Hahahahah man our mocks were so hilarious. We do good but we have moments
of spazing it out which no real interview ever has hahahaha

**Comment by wonjoolee95** [comment]
Hahaha yeah we go to random topics lol

**Comment by wonjoolee95** [comment]
Solved, please take a look :)

https://github.com/wonjoolee95/adapt-or-die/blob/master/heap/KClosest.java

**Comment by Noitidart** [comment]
Thanks man this is really cool. This is directly applicable to this Google frontend question - https://www.careercup.com/question?id=3538036
